-- 文件用途：在回滚事务中验证引导完成约束、账号隔离、写权限与节律历史保留。
begin;
create extension if not exists pgtap with schema extensions;
select plan(14);
insert into auth.users(id,email) values ('99000000-0000-0000-0000-000000000001','preferences-one@example.test'), ('99000000-0000-0000-0000-000000000002','preferences-two@example.test');
select ok(not has_function_privilege('anon','public.save_account_preferences(text,boolean,integer)','EXECUTE'),'Anonymous cannot write preferences');
select ok(not has_column_privilege('authenticated','public.workspace_profiles','gender','INSERT'),'Direct preference insert denied');
select ok(not has_table_privilege('authenticated','public.workspace_profiles','UPDATE'),'Direct preference update denied');
set local role authenticated;
select set_config('request.jwt.claim.sub','99000000-0000-0000-0000-000000000001',true);
select lives_ok('select public.initialize_workspace()','Legacy workspace initialization remains available');
select is((select gender from public.workspace_profiles),null::text,'Existing and new profiles start unselected');
select throws_ok($$select public.save_account_preferences(null,true,0)$$,'23514','PREFERENCES_GENDER_REQUIRED','Completion requires gender');
select throws_ok($$select public.save_account_preferences('invalid',false,0)$$,'23514','PREFERENCES_INVALID_INPUT','Invalid gender rejected');
select public.save_account_preferences('female',false,0);
insert into public.period_records(start_date) values ('2020-01-01');
select public.save_account_preferences('male',true,1);
select is((select gender from public.workspace_profiles),'male','Gender saved');
select ok((select onboarding_completed_at is not null from public.workspace_profiles),'Completion saved');
select is((select count(*) from public.period_records),1::bigint,'Switching gender preserves rhythm history');
select public.save_account_preferences('male',true,1);
select is((select preferences_version from public.workspace_profiles),2,'Repeated submission is idempotent');
select throws_ok($$select public.save_account_preferences('female',false,1)$$,'40001','PREFERENCES_CONFLICT','Stale device cannot overwrite');
select set_config('request.jwt.claim.sub','99000000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.workspace_profiles),0::bigint,'Other account cannot read preferences');
select public.initialize_workspace();
select public.save_account_preferences('female',true,0);
select is((select gender from public.workspace_profiles),'female','Second account writes only its own profile');
select * from finish();
rollback;
