create table projects (id uuid primary key, name text not null, color text not null, status text not null check (status in ('active','archived')), created_at timestamptz not null default now(), archived_at timestamptz);
create table tasks (id uuid primary key, project_id uuid not null references projects(id), title text not null, scheduled_date date, planned_start_time time, planned_end_time time, planned_duration_minutes integer, actual_duration_minutes integer, completed boolean not null default false, completed_at timestamptz, status text not null check (status in ('active','rescheduled','backlog','abandoned','trashed')), postponed_from date, postponed_to date, abandoned_at timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table daily_definitions (id uuid primary key, project_id uuid not null references projects(id), title text not null, active boolean not null default true, created_at timestamptz not null default now());
create table daily_instances (id uuid primary key, definition_id uuid not null references daily_definitions(id), instance_date date not null, completed boolean not null default false, actual_duration_minutes integer, result text, unique(definition_id, instance_date));
create table daily_subtasks (id uuid primary key, definition_id uuid not null references daily_definitions(id), title text not null, position integer not null);
create table daily_subtask_instances (id uuid primary key, instance_id uuid not null references daily_instances(id), subtask_id uuid not null references daily_subtasks(id), completed boolean not null default false, unique(instance_id, subtask_id));
create table history_events (id uuid primary key, task_id uuid references tasks(id), daily_instance_id uuid references daily_instances(id), event_type text not null, occurred_at timestamptz not null default now(), payload jsonb);
create table daily_close_records (id uuid primary key, close_date date not null unique, closed_at timestamptz not null default now(), project_minutes jsonb not null default '{}'::jsonb);
alter table projects enable row level security; alter table tasks enable row level security; alter table daily_definitions enable row level security; alter table daily_instances enable row level security; alter table daily_subtasks enable row level security; alter table daily_subtask_instances enable row level security; alter table history_events enable row level security; alter table daily_close_records enable row level security;
